name: update issue
on:
  issues:
    types: opened
  issue_comment:
    types: created
jobs:
  echo-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Create messages for new issue
      if: github.event_name == 'issues' && github.event.action == 'opened'
      env:
        TITLE: ${{ github.event.sender.login}} が新しい issue を公開しました
        ISSUE_TITLE: ${{ github.event.issue.title}}
        ISSUE_LINK: ${{ github.event.issue.html_url }}
      run: echo -ne "${TITLE}\n${ISSUE_TITLE}\n${ISSUE_LINK}" > contents

    - name: Create messages for new comments
      if: github.event_name == 'issue_comment' && github.event.action == 'created'
      env:
        TITLE: ${{ github.event.sender.login}} がコメントしました
        ISSUE_TITLE: ${{ github.event.issue.title}}
        ISSUE_LINK: ${{ github.event.comment.html_url }}
      run: echo -ne "${TITLE}\n${ISSUE_TITLE}\n${ISSUE_LINK}" > contents

    - name: Run | Show content
      run: |
        cat contents

