name: update issue
on:
  issues:
    types: opened
  issue_comment:
    types: created
jobs:
  echo-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Create messages for new issue
      if: github.event_name == 'issues' && github.event.action == 'opened'
      env:
        ISSUE_TITLE: ${{ github.event.issue.title}}
        ISSUE_CONTENT: ${{ github.event.issue.body }}
        ISSUE_ID: ${{ github.event.issue.number }}
      run: |
        jq -n \
        --arg title "$ISSUE_TITLE" \
        --arg content "$ISSUE_CONTENT" \
        --arg issue_id "$ISSUE_ID" \
        '{"title": $title, "content": $content, "issue_id": $issue_id}' > contents.json

    - name: Create messages for new comments
      if: github.event_name == 'issue_comment' && github.event.action == 'created'
      env:
        ISSUE_TITLE: ${{ github.event.issue.title}}
        ISSUE_CONTENT: ${{ github.event.comment.body }}
        ISSUE_ID: ${{ github.event.issue.number }}
      run: |
        jq -n \
        --arg title "$ISSUE_TITLE" \
        --arg content "$ISSUE_CONTENT" \
        --arg issue_id "$ISSUE_ID" \
        '{"title": $title, "content": $content, "issue_id": $issue_id}' > contents.json

    - name: Run | Show content
      run: |
        cat contents.json

