name: update issue
on:
  issues:
    types: opened
  issue_comment:
    types: created
jobs:
  echo-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Create messages for new issue
      if: github.event_name == 'issues' && github.event.action == 'opened'
      env:
        ISSUE_TITLE: ${{ github.event.issue.title}}
        ISSUE_CONTENT: ${{ github.event.issue.body }}
      run: echo -ne "${ISSUE_TITLE}\n${ISSUE_CONTENT}" > contents

    - name: Create messages for new comments
      if: github.event_name == 'issue_comment' && github.event.action == 'created'
      env:
        ISSUE_TITLE: ${{ github.event.issue.title}}
        ISSUE_CONTENT: ${{ github.event.comment.body }}
      run: echo -ne "${ISSUE_TITLE}\n${ISSUE_CONTENT}" > contents

    - name: Run | Show content
      run: |
        cat contents

